### ISSUE TITLE
Build failure 

### ISSUE THREAD

**Issue by clemencyworld1** [shadichy/systemback-archlinux#2]
I couldn't get the package to install. After cloning the repository and cd into its directory, I issued the "makepkg -si" command as per first instruction. This results to "unable to source PKGBUILD; unexpected end of file"

Using the second instruction, cd into systemback directory; issued "dpkg-buildpackage" give error "command not found" . I issued "rebuild" also and got the same error.

Is there anything am not doing right or package am missing. I have dpkg, debtap and debhelper installed.

Thanks

**Comment by shadichy** [comment]
I'm so sorry for this unwanted problem
But as I've mentioned, at this time right now you are unable to build these packages yet

**Comment by shadichy** [comment]
Hi @clemencyworld1 
I'm glad to tell you that now you can successfully build this package 
But beware it may breaks your system :))

**Comment by clemencyworld1** [comment]
Ok. I will try it

**Comment by clemencyworld1** [comment]
Unfortunately I managed to build and install it but could not get it to run.

Initially it complained of not being able to load "xcb" plugin and failure to connect to display. After installing qt5 and qty base packages, the error disappeared but I started getting segmentation fault.

**Comment by clemencyworld1** [comment]
I can't post the errors now as am on Android now. But some of the errors include looking for paths:
/usr/lib/qt/plugins/accessible
/isr/lib/systemback/accessible; which I checked and does not exist.

The last message was "/usr/bin/systemback: line 29: 12279 Segmentation fault

**Comment by clemencyworld1** [comment]
I just want to have a working base with my choice applications I will reinstall if I run into system errors. Unfortunately Archiso in not that intuitive.

**Comment by shadichy** [comment]
Hi

Did you get the latest source code?
Did you run it with `sudo` privilege?
Can you give me the full output of `/usr/lib/systemback/sbbin` and `journalctl -b`?

**Comment by shadichy** [comment]
and do your machine have `gcc11` and `gcc11-libs` installed?

**Comment by clemencyworld1** [comment]
> Hi
> 
> Did you get the latest source code? Did you run it with `sudo` privilege? Can you give me the full output of `/usr/lib/systemback/sbbin` and `journalctl -b`?

Ok. I used the aur package. Will use the GitHub direct source and see the difference. My thought is that the aur package downloads from the GitHub. Did not check the pkgbuild.
