### ISSUE TITLE
Error on attempting to create live image

### ISSUE THREAD

**Issue by ShaunTheSalvo** [shadichy/systemback-archlinux#5]
![Screenshot_20220808_192507](https://user-images.githubusercontent.com/110704527/183389533-f23ab722-d815-4159-b0eb-ac06c8e05647.png)

Error received when attempting to create Live System. After starting Systemback, click Live System Create, and then Create New.

**Comment by shadichy** [comment]
partially fixed, you can build from the latest source and then test it out.

**Comment by ShaunTheSalvo** [comment]
Hi,

First of all, my apologies for delay in getting back to you. At present my wife is unwell with a mild dose of covid, so I'm currently Chief Cook & Bottle-Washer around here :) .

Installed the new version of Systemback just now. When entering Live System Create screen, all options under Live Operations are greyed out, and cannot be clicked on (screenshot attached).

I've attached the `journalctl -b` output as well.

One other point I noted is that after running Systemback, `/var/lib/pacman/db.lck` is created, and is not removed, even after exiting Systemback. Unable to install packages with pacman etc. afterward, and need to run `sudo rm -rf /var/lib/pacman/db.lck` in order to be able to install anything with pacman.

Hope this information is helpful to you. All the best - Shaun.



[systemback.txt](https://github.com/shadichy/systemback-archlinux/files/9290970/systemback.txt)
![Screenshot_20220809_231701](https://user-images.githubusercontent.com/110704527/183657756-94648f12-84aa-417d-a0cb-3d98d03bd8fa.png)

**Comment by shadichy** [comment]
Please change your working directory! Systemback won't process on non-writable/not owned filesystems.

**Comment by ShaunTheSalvo** [comment]
Hi,

I uninstalled and reinstalled Systemback today, and ran it again. This time the "Create New" button under "Live Operations" was active - I have no idea what the problem was last night. Just trying to back up to /home directory as per default.

Still getting the same error - screenshot and journctl -b output below.

I tried running it from a terminal using `sudo systemback`, and got this error, printed in red in the terminal:

```
An error occurred while executing the following command:

  systemctl stop mongod

 Exit code: 5


 This file could not be copied because it does not exist:

  /boot/vmlinuz-5.18.16-arch1-1
```

I've tried installing `mongodb-bin` and `mongosh-bin` from AUR, but the error still exists. From what I can gather, mongod is just a documentation library of some kind. I never need to install mongod when running Systemback on Debian, so don't know if it's necessary for Arch.

I suspect the elephant in the room is the error about vmlinuz-5.18.16-arch1-1. I tried `sudo cp /boot/vmlinuz-linux /boot/vmlinuz-5.18.16-arch1-1`, and running Systemback again. This time the error was:

```
An error occurred while cloning the following file:

  /boot/vmlinuz-5.18.16-arch1-1

 Target file:

  /home/.sblivesystemcreate/boot/vmlinuz-.img
```
I'm not sure what is happening here.

journalctl -b output is attached.



[journalctl.txt](https://github.com/shadichy/systemback-archlinux/files/9296748/journalctl.txt)

**Comment by shadichy** [comment]
Hi

Can you please rebuild from source instead?

**Comment by ShaunTheSalvo** [comment]
Yep for sure. I'll try that, and let you know how it goes. May not be until tomorrow though.

**Comment by ShaunTheSalvo** [comment]
I decided to go ahead and compile it tonight. :) And what a nice surprise! Successfully created a bootable live ISO of my Arch system!

Well done - what a great job, congratulations. The ISO creation went through without a hitch.

I attempted to write the ISO to a USB through Systemback. The write went through to 100%, and then "Emptying cache", but then crashed with an error "The live write is aborted! There have been critical changes to the file system."

```
[arch@arch-aspiree1531 ~]$ sudo systemback
[sudo] password for arch: 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
mkfs.fat 4.2 (2021-01-31)
1+0 records in
1+0 records out
440 bytes copied, 0.0226542 s, 19.4 kB/s
sh: line 1: mcopy: command not found
/usr/sbin/syslinux: failed to create ldlinux.sys

 An error occurred while executing the following command:

  syslinux -ifd syslinux /dev/sdf1

 Exit code: 1
```

I tried copying the ISO onto a USB with Ventoy installed (allowing booting from any ISO copied onto the USB), and booted from that.

I was able to boot into the live USB (by the way, nice little touch on the boot-up menu screen!), and load the live system.

I attempted to start Systemback to see if I could install the system onto a spare partition on my HDD. After asking for my super user password, Systemback opened a window saying it was going to start making a snapshot of the system, rather than opening the normal opening window, offering the option "System Install". So at this point, I was unable to install the system from the live USB.

Other than that, the live system seemed to work fine. I tried running a few applications in the live environment, no problem at all.

Looking very good so far. Excellent work!

**Comment by shadichy** [comment]
My bad :) Will add `mtools` as a dependency!

Btw, thank you for the response!

**Comment by ShaunTheSalvo** [comment]
Good morning - wow, that was definitely a huge step forward! I installed `mtools` via pacman, and tried making a live ISO again. It's looking very good so far...

**What works:**

- installation of Systemback from source: _I needed to install `gcc11`, `dpkg` and `debhelper` from AUR (via `yay`) for the source to compile successfully_
- creating live ISO from running Arch system
- writing live ISO to USB stick (works as long as `mtools` is installed)
- booting live system from USB stick: _the live boot process is entertaining. It displays a list of messages "Looking for /dev/sda | Looking for /dev/sda1 | Looking for /dev/sda2" and so on. It then clears the screen, and displays "bruh" in ASCII-art text, and underneath that, another error message "Failed to unlink donkey". I never knew my donkey was linked in the first place :) - but nonetheless, the live system then boots. The live system runs very nicely, I tried running a few programs such as Microsoft Edge and text editors - all running perfectly._
- creation of snapshots
- restoring snapshots: _I tested this by making a snapshot, then removing some packages from my system such as web browser (I use Microsoft Edge), and a couple of small utilities like text editors - and then restoring the snapshot. All removed packages were restored and run perfectly_

**What partially works:**

- System Copy: _The System Copy process itself runs fine, but the resultant copy would not boot. It crashed at "grub rescue". I tried to reinstall GRUB in Arch, which did not work - `grub-install` froze (I waited about 30 minutes). I then rebooted into my existing Debian system, and ran `grub-install` from there, which worked, and allowed me to boot into the Systemback-copied Arch system. The copied system seems to be working perfectly._

**What doesn't work:**

- Starting Systemback from live system (to attempt to install the system to HDD): _attempting to run Systemback opens a normal system superuser prompt, asking for my password. After providing the password, instead of the normal Systemback main screen opening, the below window opens:_
![live-screenshot](https://user-images.githubusercontent.com/110704527/184066048-d6ca5f92-8524-466b-8c7c-05eaef5c2fcd.png)

Overall, the program is stable and works as normal, other than the points I mentioned above.

I don't know if it has anything useful in it, but here is my attempt to capture a journalctl -b from within the live system:

[liveboot-journalctl.txt](https://github.com/shadichy/systemback-archlinux/files/9306142/liveboot-journalctl.txt)

**Comment by shadichy** [comment]
> Starting Systemback from live system (to attempt to install the system to HDD): attempting to run Systemback opens a normal system superuser prompt, asking for my password. After providing the password, instead of the normal Systemback main screen opening, the below window opens:
You may opened `Systemback scheduler` instead of `Systemback`

**Comment by ShaunTheSalvo** [comment]
> You may opened `Systemback scheduler` instead of `Systemback`

Hi - just tried it again from the Live USB. I ran it from a terminal: tried `sudo systemback`, `sudo /usr/bin/systemback`, and also `/usr/bin/sbsustart systemback` - the same result.

If I click "Later", the program exits. If I click "Start", it tries to create a restore point in /home/systemback (within the live environment).

I've also tried deleting /etc/systemback/systemback.conf (within the live environemnt) - no change.

I've tried directly running /usr/lib/systemback/sbbin from live - the same result, just the popup asking to create a snapshot. I checked the file sizes for files for systemback in /usr/bin and in /usr/lib/systemback, and they seem to be identical. Have also tried redoing the live ISO - again, the same result.

Sorry - I can't think of anything else to try at this point. I have attached a journalctl from the live system, I'm not sure if there's anything there that may help.

[journalctl-live.txt](https://github.com/shadichy/systemback-archlinux/files/9308358/journalctl-live.txt)

**Comment by shadichy** [comment]
Can you give me your iso?

**Comment by ShaunTheSalvo** [comment]
> Can you give me your iso?

Sure. I'll upload it tomorrow (I'll try to shrink the system down a bit first- the iso is 1.9GB [!]).

**Comment by shadichy** [comment]
> Hi - just tried it again from the Live USB. I ran it from a terminal: tried sudo systemback, sudo /usr/bin/systemback, and also /usr/bin/sbsustart systemback - the same result.

Have you tried `sbsustart finstall` yet?

**Comment by ShaunTheSalvo** [comment]
> Have you tried `sbsustart finstall` (ofc, with root perm) yet?

I just tried that now (I was not aware of that command); same result (asks to create a restore point).

I'm uploading a copy of my ISO to my Google Drive, I'll give you the link later when it's finished.

**Comment by ShaunTheSalvo** [comment]
Here is a link to the ISO on my Google Drive - let me know if any issues with downloading it etc.

[https://drive.google.com/file/d/11GYDzo9dbHdvvsBYKGQ49D8WanjXwFJN/view?usp=sharing](url)

**Comment by shadichy** [comment]
I don't have your user password :)

**Comment by ShaunTheSalvo** [comment]
> I don't have your user password :)

Ugh - sorry, my bad there. Try this link:

https://drive.google.com/file/d/11GYDzo9dbHdvvsBYKGQ49D8WanjXwFJN

**Comment by ShaunTheSalvo** [comment]
BTW I'm going to try doing a full clean install of Arch again this afternoon (should be fun), and try a clean install of Systemback onto that, and see how that goes.

**Comment by shadichy** [comment]
I used pear os arch on vm and created an pear os iso, booted in, and systemback was launching successfully
Dunno how

**Comment by ShaunTheSalvo** [comment]
It's got me baffled. Anyway, I have my clean install of Arch underway - just the official ISO with their oh-so-friendly installer. So give me an hour or so, and I will hopefully have a new Systemback ISO built and test it.

By the way, if I can load Systemback from the ISO, is the installer section ported yet, ie should be possible to install Arch from the ISO?

**Comment by ShaunTheSalvo** [comment]
Well - I did a clean install of Arch, using the official Arch installer ISO. Then installed Systemback, and completed the live ISO (which actually came up slightly bigger -2.1GB - nothing else installed on the system except Microsoft Edge ... weird).

Unfortunately - same result. Asked for password, then brought up window in top right of screen asking to make a snapshot.

Baffled.

**Comment by shadichy** [comment]
@ShaunTheSalvo Please rebuild from source again. I've just uploaded a patch!

**Comment by ShaunTheSalvo** [comment]
Hi Shadichy,

Nice work! :) Systemback will now start correctly, and will even allow me to attempt to install the system. The install process runs through without any problems; it will allow me to select/change partitions as per the normal function in Systemback.
However, attempting to boot the installed system returns the following error message:

```
error: no such device: 4881-4C34
Loading Linux linux ...
error: file `/vmlinuz-linux' not found.
Loading initial ramdisk ...
error: you need to load the kernel first.

Press any key to continue..._
```

I do have a question: do you have any preference if I'm using UEFI or BIOS boot mode (my laptop can do both)? The Arch system I'm using (and resultant live ISO) were created under BIOS mode. The USB I created will boot fine under BIOS mode, but will _not_ boot under UEFI mode.

I can reinstall Arch in UEFI mode, and try again, if that would help.

Hope this info is helpful. Again, I wanted to say that I greatly appreciate your hard work, and the time you're investing into this.

**Comment by shadichy** [comment]
Sorry, my bad! Will fix it asap!

Btw,
> There is another error message that briefly flashes (for about a second) after the list of /dev/sdx scrolls up the screen, but it disappears before I can really look at it. I'm trying to grab a photo of it, but my 50-year-old reflexes ain't what they used to be :) - I'll keep trying though.

is not a bug :) It's live root detector hook proccessing :)

**Comment by shadichy** [comment]
> BTW, still curious on the UEFI/BIOS issue.

Handled, this update supports both `x86_64-efi`, `i386-efi` (grub) and bios boot (grub with `i386-pc` and syslinux bios)

**Comment by shadichy** [comment]
> I do have a question: do you have any preference if I'm using UEFI or BIOS boot mode (my laptop can do both)? The Arch system I'm using (and resultant live ISO) were created under BIOS mode. The USB I created will boot fine under BIOS mode, but will not boot under UEFI mode.

Sorry about that, it's a small grub bug! Partially fixed for now!

**Comment by shadichy** [comment]
> > I do have a question: do you have any preference if I'm using UEFI or BIOS boot mode (my laptop can do both)? The Arch system I'm using (and resultant live ISO) were created under BIOS mode. The USB I created will boot fine under BIOS mode, but will not boot under UEFI mode.
> 
> Sorry about that, it's a small grub bug! Partially fixed for now!

fully fixed! Sorry for this impatience!

**Comment by ShaunTheSalvo** [comment]
You, sir, are a gentleman and a scholar!

I will test tomorrow and let you know how it goes.

**Comment by shadichy** [comment]
> You, sir, are a gentleman and a scholar!
> 
> I will test tomorrow and let you know how it goes.

Thank you! Thank you so much for your donation!!! Appreciate it! I don't know how to describe how I'm feeling! So Happy! Thank you so much! Love you <3
