### ISSUE TITLE
Two errors when attempting to install from live USB

### ISSUE THREAD

**Issue by ShaunTheSalvo** [shadichy/systemback-archlinux#6]
Hi Shadichy,

Just letting you know, still unable to install Arch from a live ISO (created this morning). When running using `sudo systemback`, the following error appears at the end of install.

```
/dev/sdc3 contains a ext4 file system labelled 'SB@home'
        last mounted on /.sbsystemcopy/home on Mon Aug 15 09:10:11 2022
Creating filesystem with 116853510 4k blocks and 29220864 inodes
Filesystem UUID: f3164dbc-9f66-4964-846f-ee0711cc16a7
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
        4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968, 
        102400000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: done     

mkswap: /dev/sdc2: warning: wiping old swap signature.
Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
LABEL=SB@SWAP, UUID=59e51daf-a0a2-43ae-8cec-bd220d052892
Checking if username is valid

 An error occurred while executing the following command:

  grep -Fxq fred "/usr/share/systemback/reserved_usernames"

 Exit code: 1 
```

**I found a workaround** - it seems SB is failing when the given username does NOT appear in `/usr/share/systemback/reserved_usernames`. I tried deleting that file (within the live system), and creating a new file with the same name, and including just the username I'm using to install. This will then allow the install to complete without errors.

Also, still appears the GRUB error is still occurring. After trying to boot into the newly installed system, the boot fails and I get a grub> prompt.

**Comment by shadichy** [comment]
> Also, still appears the GRUB error is still occurring. After trying to boot into the newly installed system, the boot fails and I get a grub> prompt.

Sir, can you give me your `/boot/grub/grub.cfg` (after installing) please?

**Comment by shadichy** [comment]
> Also, still appears the GRUB error is still occurring. After trying to boot into the newly installed system, the boot fails and I get a grub> prompt.

Also, in grub> shell (installed system), `set pager=1`, `lsmod`, `set` and give me the output (text or screenshot) if available. Thanks!

**Comment by ShaunTheSalvo** [comment]
> Sir, can you give me your `/boot/grub/grub.cfg` (after installing) please?

I'd love to ... except it does not exist. 

During an install from live USB in terminal using `sudo systemback`, returns the following error (I have attached the full terminal log):

```
/usr/bin/grub-probe: error: failed to get canonical path of `/boot'.
Installing for i386-pc platform.
Installation finished. No error reported.
```

Also attached screenshots from grub rescue as requested.
![grubrescue-1](https://user-images.githubusercontent.com/110704527/184596753-5e0fc617-89de-4291-b6f0-f4762cb64d53.jpg)
![grubrescue-2](https://user-images.githubusercontent.com/110704527/184596763-594c4481-3378-40b1-b75c-419895bd66dc.jpg)
![grubrescue-3](https://user-images.githubusercontent.com/110704527/184596764-47842d90-a9d0-456c-bf18-54af4a2a6168.jpg)
[sb-installation-log.txt](https://github.com/shadichy/systemback-archlinux/files/9335799/sb-installation-log.txt)
[grub-dir-listing.txt](https://github.com/shadichy/systemback-archlinux/files/9335800/grub-dir-listing.txt)

**Comment by shadichy** [comment]
Grub somehow didn't generate config file
Btw fixed for now. You can try building from source. 

Thanks!

**Comment by ShaunTheSalvo** [comment]
> Grub somehow didn't generate config file Btw fixed for now. You can try building from source.
> 
> Thanks!

Shall do, and will let you know (probably tomorrow) how it goes.

Thanks again.

**Comment by ShaunTheSalvo** [comment]
Good morning,

Very impressive, my friend! Managed to successfully install Arch from a Systemback image! Everything appears to be working fine on the newly installed system.

Unfortunately, there was one issue. **I was unable to log in to my desktop when I tried installing without copying the user data files.** It seems there was some problem with SB creating the new user. When I logged in to the system (I'm using KDE/Plasma, BTW), it would not accept the password I provided in Systemback. A workaround was to create a new user manually after installing (using CTRL+ALT+F2 to get to a terminal), and then logging in using the newly created user.

I tried another install this morning, this time with `Copy the user data files` ticked during the install. The resultant system booted with no problems whatsoever. First time I have successfully installed Arch from a Systemback image! :)

So yeah - it's looking really good!

**Comment by shadichy** [comment]
> Unfortunately, there was one issue. I was unable to log in to my desktop when I tried installing without copying the user data files. It seems there was some problem with SB creating the new user. When I logged in to the system (I'm using KDE/Plasma, BTW), it would not accept the password I provided in Systemback. A workaround was to create a new user manually after installing (using CTRL+ALT+F2 to get to a terminal), and then logging in using the newly created user.

Sorry about this, this is a Systemback related issue!
I'm not sure whether I can fix it or not.

Btw thank you for your response!
Have a good day!

**Comment by shadichy** [comment]
> Unfortunately, there was one issue. I was unable to log in to my desktop when I tried installing without copying the user data files. It seems there was some problem with SB creating the new user. When I logged in to the system (I'm using KDE/Plasma, BTW), it would not accept the password I provided in Systemback. A workaround was to create a new user manually after installing (using CTRL+ALT+F2 to get to a terminal), and then logging in using the newly created user.

I don't know why but when I replicate this I have no problem with my installation
Can you show me your installed system `/etc/shadow` file?

**Comment by ShaunTheSalvo** [comment]
> I don't know why but when I replicate this I have no problem with my installation Can you show me your installed system `/etc/shadow` file?

I don't have that particular installed system available, as I reused my spare HDD to reinstall this morning with `Include the user data files` ticked. So unfortunately, I can't provide that file from the faulty install.

However, I tried again just now to reinstall with `Include the user data files` unticked ... This time, the installation went through without any problems. In fact, I'm writing this now from within the newly installed system. So maybe something just went wrong during the install last night? Sorry I can't be more help on that one.

**MORE TESTING  :) - All these have simple workarounds that work nicely** 

- The other issue I mentioned in the first post on this thread (about problems with `/usr/share/systemback/reserved_usernames`) seems to be resolved as well! Seems I can install using just about any username I like - within reason, of course.
- Just for the fun of it, I've tried using "System Upgrade" from within SB - the upgrade itself ran fine (I assume it just runs `sudo pacman -Syu`). However after the upgrade completes, an Xterm window pops up saying "An error occurred while upgrading the system!" and "Restart upgrade ..." - and a countdown 3 - 2 - 1. This continues to cycle until I close the window. The upgrade itself seems to be completing successfully however, so probably just a cosmetic thing.
- `/var/lib/pacman/db.lck` is created when starting SB, but occasionally is not removed when exiting the program. So attempts to use pacman etc. after running SB sometimes will not work. Deleting the file with `sudo rm -rf` after exiting SB seems to work; I can then run pacman etc.
_WORKAROUND:_ I came up with a simple workaround of adding `; sudo rm -rf /var/lib/pacman/db.lck` to the command line for running SB (so you get `sbsustart systemback; sudo rm -rf /var/lib/pacman/db.lck`).
- Unable to directly select external devices (eg external hard drive) to use for working/storage directories for restore points and live system creation. This is likely due to the difference in how Debian and Arch handle external media.
In Debian, the path is `/media/username/device`, so for my external HDD called Backup, the path is `/media/shaun/Backup`.
In Arch on the other hand, the path is `/run/media/username/device` (ie `/run/media/shaun/Backup`). The `/media` directory exists on my Arch system, but seems to be empty, and not being used in any way.
_WORKAROUND:_  I deleted the existing `/media/` directory, then ran `sudo ln -s /run/media /media`. I can now select my external HDD in Arch to use for both live system creation, and restore point creation.

**Comment by shadichy** [comment]
> Just for the fun of it, I've tried using "System Upgrade" from within SB - the upgrade itself ran fine (I assume it just runs sudo pacman -Syu). However after the upgrade completes, an Xterm window pops up saying "An error occurred while upgrading the system!" and "Restart upgrade ..." - and a countdown 3 - 2 - 1. This continues to cycle until I close the window. The upgrade itself seems to be completing successfully however, so probably just a cosmetic thing.

disabled old kernel removal (just for arch, as it's a rolling distro :))

> /var/lib/pacman/db.lck is created when starting SB, but occasionally is not removed when exiting the program. So attempts to use pacman etc. after running SB sometimes will not work. Deleting the file with sudo rm -rf after exiting SB seems to work; I can then run pacman etc.
WORKAROUND: I came up with a simple workaround of adding ; sudo rm -rf /var/lib/pacman/db.lck to the command line for running SB (so you get sbsustart systemback; sudo rm -rf /var/lib/pacman/db.lck).

added `auto unlock` script after exit in `/usr/bin/systemback`

> Unable to directly select external devices (eg external hard drive) to use for working/storage directories for restore points and live system creation. This is likely due to the difference in how Debian and Arch handle external media.
In Debian, the path is /media/username/device, so for my external HDD called Backup, the path is /media/shaun/Backup.
In Arch on the other hand, the path is /run/media/username/device (ie /run/media/shaun/Backup). The /media directory exists on my Arch system, but seems to be empty, and not being used in any way.

temporarily create symlink `/media` to `/run/media` at start

**Comment by ShaunTheSalvo** [comment]
> Will manage to fix it soon, first need to remove old kernel handler (as arch has no old kernel :))

All good, don't stress over it. 


> Arch doesn't use `/media`, thus, it has no effect on your arch system. As it's unnecessary, you don't need to
> 
> > Added rm /media && mkdir /media to the end of /usr/bin/systemback - it now reverts to a normal directory (as it was) when exiting SB

Thanks for the info! :) Appreciate you letting me work with you on this, as it's also helping me learn more about Arch, and of course Linux in general. I've been using Linux for about 15+ years, and loving it.

**Comment by shadichy** [comment]
> I've been using Linux for about 15+ years, and loving it.

Really admire you! I've just been using it for nearly 2years. You must be very experienced!

Thank you for helping me finding bugs :)
